confirm-gui:
  title: "&8Xác nhận: &1%crate%"
  # Cấu hình Slot
  cancel-slot: 11
  display-slot: 13
  confirm-slot: 15
  
  # Cấu hình Item
  cancel:
    material: RED_STAINED_GLASS_PANE
    name: '&#fc0404ᴄᴀɴᴄᴇʟ'
    lore:
      - '&fClick to cancel the sale'
      
  confirm:
    material: LIME_STAINED_GLASS_PANE
    name: '&#04fc04ᴄᴏɴғɪʀᴍ'
    lore:
      - '&fClick to sell'
