name: ArisCrate
version: 1.1
main: me.aris.ariscrate.ArisCrate
api-version: 1.20
folia-supported: true
author: Aris
description: Advanced crate plugin with key system

commands:
  ariscrate:
    description: Main command for ArisCrate
    usage: /acrate help
    aliases: [acrate]

permissions:
  ariscrate.admin:
    description: Admin permissions for ArisCrate
    default: op
