name: ArisCrate
version: 1.0
main: me.aris.crates.ArisCrate
api-version: 1.20
commands:
  ariscrate:
    description: Lenh quan ly ruong ArisCrate
    aliases: ac
permissions:
  ariscrate.admin:
    description: Quyen quan ly admin cho ArisCrate
    default: op
folia-supported: true
